# Generated by Django 2.2.1 on 2019-05-18 07:29

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('category', models.CharField(choices=[('', 'select'), ('Junior', 'Upto 13 yrs'), ('Senior', 'Above 13 yrs')], max_length=12, verbose_name='Category')),
                ('contact', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Contact')),
                ('addess', models.CharField(max_length=100, verbose_name='Address')),
                ('payment', models.BooleanField(default=True)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('txn_date', models.DateTimeField(blank=True, null=True)),
                ('SPR_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='rangotsav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('', 'select'), ('Junior', 'Below 13 years'), ('Senior', 'Above or equal to 13 yrs')], max_length=12, verbose_name='Category')),
                ('Full_name1', models.CharField(max_length=50, verbose_name='Full Name')),
                ('contact_1', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Contact')),
                ('addess1', models.CharField(max_length=100, verbose_name='Address')),
                ('Full_name2', models.CharField(max_length=50, verbose_name='Full Name')),
                ('address_2', models.CharField(max_length=100, verbose_name='Address')),
                ('contact_2', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Contact')),
                ('Full_name3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Full Name')),
                ('address_3', models.CharField(blank=True, max_length=100, verbose_name='Address')),
                ('contact_3', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Contact')),
                ('payment', models.BooleanField(default=True)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('txn_date', models.DateTimeField(blank=True, null=True)),
                ('rangotsav_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mother Name')),
                ('father_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Father Name')),
                ('class_study', models.PositiveIntegerField(default=5, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)], verbose_name='Class Study')),
                ('post_office', models.CharField(blank=True, max_length=50, null=True, verbose_name='Post Office')),
                ('gender', models.CharField(blank=True, choices=[('', 'select'), ('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=50, verbose_name='Gender')),
                ('addess', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('landmark', models.CharField(blank=True, max_length=50, null=True, verbose_name='Landmark')),
                ('birth_date', models.DateField(default=datetime.date.today, verbose_name='Date of birth')),
                ('ditrict', models.CharField(blank=True, max_length=50, null=True, verbose_name='District')),
                ('pin', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='Pin')),
                ('Home_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Home Number')),
                ('contact', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Contact')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='PR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('', 'select'), ('Junior', 'VII/VIII'), ('Senior', 'IX/X')], max_length=12, verbose_name='Category')),
                ('Full_name1', models.CharField(max_length=50, verbose_name='Full Name 1')),
                ('class1', models.CharField(choices=[('', 'select'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, verbose_name='Class')),
                ('contact_1', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Contact')),
                ('addess1', models.CharField(max_length=100, verbose_name='Address')),
                ('Full_name2', models.CharField(max_length=50, verbose_name='Full Name 2')),
                ('class2', models.CharField(choices=[('', 'select'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, verbose_name='Class')),
                ('address_2', models.CharField(max_length=100, verbose_name='Address')),
                ('contact_2', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Contact')),
                ('Full_name3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Full Name 3')),
                ('class3', models.CharField(blank=True, choices=[('', 'select'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True, verbose_name='Class')),
                ('address_3', models.CharField(blank=True, max_length=100, verbose_name='Address')),
                ('contact_3', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Contact')),
                ('payment', models.BooleanField(default=False)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('txn_date', models.DateTimeField(blank=True, null=True)),
                ('PR_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MTSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qpl', models.CharField(choices=[('', 'select'), ('English', 'English'), ('Hindi', 'Hindi')], max_length=9, verbose_name='Paper langauge')),
                ('father_name', models.CharField(max_length=50, verbose_name='Father Name')),
                ('mother_name', models.CharField(max_length=50, verbose_name='Mother Name')),
                ('st_class', models.CharField(choices=[('', 'select'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, verbose_name='Class')),
                ('board', models.CharField(choices=[('', 'select'), ('BSEB', 'BSEB'), ('CBSE', 'CBSE')], max_length=6, verbose_name='Board')),
                ('school', models.CharField(max_length=50, verbose_name='School')),
                ('post_office', models.CharField(max_length=50, verbose_name='Post Office')),
                ('birth_date', models.DateField(default=datetime.date.today, verbose_name='Date of birth')),
                ('gender', models.CharField(choices=[('', 'select'), ('Female', 'Female'), ('Male', 'Male')], max_length=50, verbose_name='Gender')),
                ('landmark', models.CharField(max_length=50, verbose_name='Landmark')),
                ('addess', models.CharField(max_length=100, verbose_name='Address')),
                ('ditrict', models.CharField(max_length=50, verbose_name='District')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('pin', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='Pin')),
                ('Home_number', models.CharField(max_length=10, verbose_name='Home Number')),
                ('payment', models.BooleanField(default=False)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('txn_date', models.DateTimeField(blank=True, null=True)),
                ('MTSE_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FHS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('', 'select'), ('Junior', 'V/VI/VII'), ('Senior', 'VIII/IX/X')], max_length=12, verbose_name='Category')),
                ('contact', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Contact')),
                ('addess', models.CharField(max_length=100, verbose_name='Address')),
                ('payment', models.BooleanField(default=False)),
                ('txn_date', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('FHS_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='chess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('', 'select'), ('G1', 'Upto 13 yrs'), ('G2', 'From 14 to 17 yrs'), ('G3', 'Above 17 yrs')], max_length=12, verbose_name='Category')),
                ('contact', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Contact')),
                ('addess', models.CharField(max_length=50, verbose_name='Address')),
                ('txn_date', models.DateTimeField(blank=True, null=True)),
                ('payment', models.BooleanField(default=False)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('chess_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
