# Generated by Django 2.2 on 2019-05-11 19:10

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('Upto 13 yrs', 'JUNIOR'), ('Above 13 yrs', 'SENIOR')], max_length=12)),
                ('contact', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('addess', models.CharField(blank=True, max_length=50, null=True)),
                ('SPR_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='rangotsav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Below 13 yrs', 'JUNIOR'), ('Above or equal to 13 yrs', 'SENIOR')], max_length=12)),
                ('Full_name1', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_1', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('addess1', models.CharField(blank=True, max_length=50, null=True)),
                ('Full_name2', models.CharField(blank=True, max_length=50, null=True)),
                ('address_2', models.CharField(max_length=100)),
                ('contact_2', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('Full_name3', models.CharField(blank=True, max_length=50, null=True)),
                ('address_3', models.CharField(max_length=100)),
                ('contact_3', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('rangotsav_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('class_study', models.PositiveIntegerField(default=5, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)])),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('', 'Male')], default='Male', max_length=50)),
                ('addess', models.CharField(blank=True, max_length=50, null=True)),
                ('landmark', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(default=datetime.date.today, verbose_name='Date of birth')),
                ('ditrict', models.CharField(blank=True, max_length=50, null=True)),
                ('post_office', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(999999)])),
                ('Home_number', models.CharField(blank=True, max_length=10, null=True)),
                ('contact', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='PR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('VII/VIII', 'JUNIOR'), ('IX/X', 'SENIOR')], max_length=12)),
                ('Full_name1', models.CharField(blank=True, max_length=50, null=True)),
                ('class1', models.PositiveIntegerField(default=4, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)])),
                ('contact_1', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('addess1', models.CharField(blank=True, max_length=50, null=True)),
                ('Full_name2', models.CharField(blank=True, max_length=50, null=True)),
                ('class2', models.PositiveIntegerField(default=4, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)])),
                ('address_2', models.CharField(max_length=100)),
                ('Full_name3', models.CharField(blank=True, max_length=50, null=True)),
                ('class3', models.PositiveIntegerField(default=4, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)])),
                ('address_3', models.CharField(max_length=100)),
                ('contact_3', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('PR_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MTSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qpl', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi')], max_length=9, verbose_name='Paper langauge')),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('st_class', models.CharField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2)),
                ('board', models.CharField(choices=[('BSEB', 'BSEB'), ('CBSE', 'CBSE')], max_length=6)),
                ('class_study', models.PositiveIntegerField(default=4, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)])),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
                ('post_office', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(default=datetime.date.today, verbose_name='Date of birth')),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('', 'Male')], max_length=50, null=True)),
                ('landmark', models.CharField(blank=True, max_length=50, null=True)),
                ('addess', models.CharField(blank=True, max_length=50, null=True)),
                ('ditrict', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('pin', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(999999)])),
                ('Home_number', models.CharField(blank=True, max_length=10, null=True)),
                ('MTSE_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FHS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('V/VI/VII', 'JUNIOR'), ('VIII/IX/X', 'SENIOR')], max_length=12)),
                ('contact', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('addess', models.CharField(blank=True, max_length=50, null=True)),
                ('FHS_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='chess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('Upto 13 yrs', 'G1'), ('From 14 to 17 yrs', 'G2'), ('Above 17 yrs', 'G3')], max_length=12)),
                ('contact', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('addess', models.CharField(blank=True, max_length=50, null=True)),
                ('chess_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
