# Generated by Django 2.2 on 2019-05-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navprayas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chess',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fhs',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mtse',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pr',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rangotsav',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spr',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
