# Generated by Django 2.2 on 2019-05-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navprayas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chess',
            name='category',
            field=models.CharField(choices=[('', 'Upto 13 yrs'), ('G2', 'From 14 to 17 yrs'), ('G3', 'Above 17 yrs')], max_length=12),
        ),
        migrations.AlterField(
            model_name='fhs',
            name='category',
            field=models.CharField(choices=[('', 'V/VI/VII'), ('SENIOR', 'VIII/IX/X')], max_length=12),
        ),
        migrations.AlterField(
            model_name='mtse',
            name='board',
            field=models.CharField(choices=[('', 'BSEB'), ('CBSE', 'CBSE')], max_length=6),
        ),
        migrations.AlterField(
            model_name='mtse',
            name='qpl',
            field=models.CharField(choices=[('', 'English'), ('Hindi', 'Hindi')], max_length=9, verbose_name='Paper langauge'),
        ),
        migrations.AlterField(
            model_name='mtse',
            name='st_class',
            field=models.CharField(choices=[('', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pr',
            name='category',
            field=models.CharField(choices=[('', 'VII/VIII'), ('SENIOR', 'IX/X')], max_length=12),
        ),
        migrations.AlterField(
            model_name='rangotsav',
            name='category',
            field=models.CharField(choices=[('', 'JUNIOR'), ('SENIOR', 'Above or equal to 13 yrs')], max_length=12),
        ),
        migrations.AlterField(
            model_name='spr',
            name='category',
            field=models.CharField(choices=[('', 'Upto 13 yrs'), ('SENIOR', 'Above 13 yrs')], max_length=12),
        ),
    ]
