# Generated by Django 2.2 on 2019-05-20 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navprayas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chess',
            name='addess',
            field=models.CharField(max_length=50, verbose_name='Full Address (with House Number)'),
        ),
        migrations.AlterField(
            model_name='fhs',
            name='addess',
            field=models.CharField(max_length=100, verbose_name='Full Address (with House Number)'),
        ),
        migrations.AlterField(
            model_name='mtse',
            name='Home_number',
            field=models.CharField(max_length=10, verbose_name='House Number'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='addess1',
            field=models.CharField(max_length=100, verbose_name='Full Address (with House Number)'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='address_2',
            field=models.CharField(max_length=100, verbose_name='Full Address (with House Number)'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='address_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Full Address (with House Number)'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='contact_3',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Home_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='House Number'),
        ),
        migrations.AlterField(
            model_name='rangotsav',
            name='addess1',
            field=models.CharField(max_length=100, verbose_name='Full Address (with House Number)'),
        ),
        migrations.AlterField(
            model_name='rangotsav',
            name='address_2',
            field=models.CharField(max_length=100, verbose_name='Full Address (with House Number)'),
        ),
        migrations.AlterField(
            model_name='rangotsav',
            name='address_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Full Address (with House Number)'),
        ),
        migrations.AlterField(
            model_name='spr',
            name='addess',
            field=models.CharField(max_length=100, verbose_name='Full Address (with House Number)'),
        ),
    ]
