# Generated by Django 2.2 on 2019-05-20 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navprayas', '0002_auto_20190520_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtse',
            name='contact',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000, 'Please enter a valid 10 digit contact number'), django.core.validators.MaxValueValidator(9999999999, 'Please enter a valid 10 digit contact number')], verbose_name='Phone/Mobile'),
        ),
        migrations.AlterField(
            model_name='chess',
            name='contact',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000, 'Please enter a valid 10 digit contact number'), django.core.validators.MaxValueValidator(9999999999, 'Please enter a valid 10 digit contact number')], verbose_name='Phone/Mobile'),
        ),
        migrations.AlterField(
            model_name='fhs',
            name='contact',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000, 'Please enter a valid 10 digit contact number'), django.core.validators.MaxValueValidator(9999999999, 'Please enter a valid 10 digit contact number')], verbose_name='Phone/Mobile'),
        ),
        migrations.AlterField(
            model_name='mtse',
            name='pin',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100000, 'Please enter a valid 6 digit pin code'), django.core.validators.MaxValueValidator(999999, 'Please enter a valid 6 digit pin code ')], verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='mtse',
            name='school',
            field=models.CharField(max_length=50, verbose_name='Name of School/Coaching'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='contact_1',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000, 'Please enter a valid 10 digit contact number'), django.core.validators.MaxValueValidator(9999999999, 'Please enter a valid 10 digit contact number')], verbose_name='Phone/Mobile'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='contact_2',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000, 'Please enter a valid 10 digit contact number'), django.core.validators.MaxValueValidator(9999999999, 'Please enter a valid 10 digit contact number')], verbose_name='Phone/Mobile'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='contact_3',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000000, 'Please enter a valid 10 digit contact number'), django.core.validators.MaxValueValidator(9999999999, 'Please enter a valid 10 digit contact number')], verbose_name='Phone/Mobile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000, 'Please enter a valid 10 digit contact number '), django.core.validators.MaxValueValidator(9999999999, 'Please enter a valid 10 digit contact number')], verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000, 'Please enter a valid 6 digit pin code'), django.core.validators.MaxValueValidator(999999, 'Please enter a valid 6 digit pin code')], verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='rangotsav',
            name='contact_1',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000, 'Please enter a valid 10 digit contact number'), django.core.validators.MaxValueValidator(9999999999, 'Please enter a valid 10 digit contact number')], verbose_name='Phone/Mobile'),
        ),
        migrations.AlterField(
            model_name='rangotsav',
            name='contact_2',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000, 'Please enter a valid 10 digit contact number'), django.core.validators.MaxValueValidator(9999999999, 'Please enter a valid 10 digit contact number')], verbose_name='Phone/Mobile'),
        ),
        migrations.AlterField(
            model_name='rangotsav',
            name='contact_3',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000000, 'Please enter a valid 10 digit contact number'), django.core.validators.MaxValueValidator(9999999999, 'Please enter a valid 10 digit contact number')], verbose_name='Phone/Mobile'),
        ),
        migrations.AlterField(
            model_name='spr',
            name='contact',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000, 'Please enter a valid 10 digit contact number'), django.core.validators.MaxValueValidator(9999999999, 'Please enter a valid 10 digit contact number')], verbose_name='Phone/Mobile'),
        ),
    ]
