# Generated by Django 2.2 on 2019-05-11 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navprayas', '0002_auto_20190511_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='post_office',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
