# Generated by Django 2.2 on 2019-05-20 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navprayas', '0003_auto_20190520_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='class_study',
            field=models.PositiveIntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)], verbose_name='Class '),
        ),
    ]
