# Generated by Django 2.2 on 2019-05-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navprayas', '0004_auto_20190511_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chess',
            name='category',
            field=models.CharField(choices=[('', 'select'), ('G1', 'Upto 13 yrs'), ('G2', 'From 14 to 17 yrs'), ('G3', 'Above 17 yrs')], max_length=12),
        ),
        migrations.AlterField(
            model_name='fhs',
            name='category',
            field=models.CharField(choices=[('', ''), ('Junior', 'V/VI/VII'), ('Senior', 'VIII/IX/X')], max_length=12),
        ),
        migrations.AlterField(
            model_name='mtse',
            name='board',
            field=models.CharField(choices=[('', 'select'), ('BSEB', 'BSEB'), ('CBSE', 'CBSE')], max_length=6),
        ),
        migrations.AlterField(
            model_name='mtse',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'select'), ('Female', 'Female'), ('Male1', 'Male')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mtse',
            name='qpl',
            field=models.CharField(choices=[('', 'select'), ('English', 'English'), ('Hindi', 'Hindi')], max_length=9, verbose_name='Paper langauge'),
        ),
        migrations.AlterField(
            model_name='mtse',
            name='st_class',
            field=models.CharField(choices=[('', 'select'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pr',
            name='category',
            field=models.CharField(choices=[('', 'select'), ('Junior', 'VII/VIII'), ('Senior', 'IX/X')], max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'select'), ('Female', 'Female'), ('Male1', 'Male')], default='Male', max_length=50),
        ),
        migrations.AlterField(
            model_name='rangotsav',
            name='category',
            field=models.CharField(choices=[('', 'select'), ('Junior', 'Below 13 years'), ('Senior', 'Above or equal to 13 yrs')], max_length=12),
        ),
        migrations.AlterField(
            model_name='spr',
            name='category',
            field=models.CharField(choices=[('', 'select'), ('Junior', 'Upto 13 yrs'), ('Senior', 'Above 13 yrs')], max_length=12),
        ),
    ]
