# Generated by Django 2.2 on 2019-05-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navprayas', '0005_auto_20190511_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtse',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'select'), ('Female', 'Female'), ('Male', 'Male')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'select'), ('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=50),
        ),
    ]
