# Generated by Django 2.2 on 2019-05-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navprayas', '0007_auto_20190521_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='class_study',
            field=models.PositiveIntegerField(blank=True, choices=[('', 'select'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], null=True, verbose_name='Class'),
        ),
    ]
